### ISSUE TITLE
wheel for version 4.x built with wrong python version signature

### ISSUE THREAD

**Issue by ralhei** [jazzband/inflect#100]
Due to the universal build the wheel uploaded to pypi is called `inflect-4.0.0-py2.py3-none-any.whl` indicating that the wheel is suitable for Python 2.
However in setup.cfg has a `python_requires = >=3.6` statement.
Because if this mismatch Python2 download the wheel but fails to install it. 
The fix would probably be to remove the following section from setup.cfg:
```
[bdist_wheel]
universal = 1
```
Then the published wheel will not contain `py2` in its wheel name.

**Comment by jaraco** [comment]
Fixed in 479ac2149d872757160732bc977977ee0192ac51.
