### ISSUE TITLE
Remove Tidelift

### ISSUE THREAD

**Issue by jezdez** [jazzband/inflect#102]
Hi @jaraco,

Please remove the Tidelift integration added in https://github.com/jazzband/inflect/commit/9de62be9c9036e2ea2a9e83f15df778e77bcce15 as profiting financially from the Jazzband community is not permitted. I expect this to be completed within the week or the repo will be removed.

Jannis Leidel

**Comment by jaraco** [comment]
Please transfer the project. Thanks.

**Comment by jezdez** [comment]
The transfer request has been made.
