### ISSUE TITLE
Returns different results if the first letter is capitalized

### ISSUE THREAD

**Issue by jirick1987** [jazzband/inflect#106]
System: macOS Catalina (10.15.4)
Python 3.7.2

```python
import inflect
p = inflect.engine()
word = "company"
print(p.plural(word)) # outputs ---> 'companies'
```

Same word, the C is capitized
```python
import inflect
p = inflect.engine()
word = "Company"
print(p.plural(word)) # outputs ---> 'Companys'
```

**Comment by hugovk** [comment]
Capitalised words are treated as proper nouns.

Duplicate of https://github.com/jazzband/inflect/issues/78 and https://github.com/jazzband/inflect/issues/104.

> LEI assumes that a capitalized word is a person's name. So it forms the plural according to the rules for names (which is that you don't inflect, you just add -s or -es). You can choose to turn that behaviour off (it's on by the default, even when the module isn't in classical mode) by calling `classical(names=0)`

**Comment by jirick1987** [comment]
Thanks for the explanation.
