### ISSUE TITLE
a/an wrong on this word

### ISSUE THREAD

**Issue by fariparedes** [jazzband/inflect#107]
Whoops, finger slipped.

Anyway, engine().a() and engine().an() are wrong for the word "slip," as in "slip of paper."

Oh wait. How ironic! Anyway, fix it? Pretty please?

**Comment by jaraco** [comment]
Not sure what you expect to happen, but the current behavior matches my expectation:

```
>>> import inflect
>>> p = inflect.engine()
>>> p.a('slip')
'a slip'
>>> p.an('slip')
'a slip'
```
