### ISSUE TITLE
Past Tense and Past Participle 

### ISSUE THREAD

**Issue by Bipulkumarsingh** [jazzband/inflect#115]
word = "talked"

p.singular_noun(word)) 
Expected output
> talk
But return Flase

I tried this word with plural 
p.plural(word))
> return talkeds

**Comment by jaraco** [comment]
"talked" is the past tense of the verb "to talk", and passing any verb to `singular_noun` or `plural` is invalid. Feel free to clarify if I've misunderstood your expectation.
