### ISSUE TITLE
Conjugate (and make infinitive) verbs

### ISSUE THREAD

**Issue by pwdyson** [jazzband/inflect#2]
Already does this for nouns. Could add for verbs.

Generate the singular of a verb from the plural:
e.g.
siverb('walk') -> 'walks'
(They walk -> it walks)

**Comment by jaraco** [comment]
I welcome contributions on this ticket, but I imagine to do it will will require a level up of sophistication in the library. I'm not hopeful, so I'm going to close it as stale, but I welcome anyone to revive the effort at any time.
