### ISSUE TITLE
License problem

### ISSUE THREAD

**Issue by cool-RR** [jazzband/inflect#29]
I want to use this package in a corporate setting and the AGPL license is a problem. Is there an MIT/BSD alternative to this package?

**Comment by stevenwinfield** [comment]
[inflection](https://pypi.python.org/pypi/inflection) has some of inflect's basic functionality, and is MIT licensed.

It would be really nice to have the whole of inflect available under a more permissive license, though.

**Comment by amitjindal** [comment]
Hi, I would like to kindly request the same thing. Almost all Jazzband projects are under MIT/BSD style licenses (Sorry I didn't check all but most of them). It will really help if you can please change the licensing on this.

**Comment by slippycheeze** [comment]
Note: I was here thinking just exactly the same thing.  The [original code copyright and license statement](https://metacpan.org/pod/Lingua::EN::Inflect#COPYRIGHT) puts this explicitly under [the Perl5 license](https://dev.perl.org/licenses/), which is "GPLv1+, or Artistic".

Damien was always very careful about license selection, and intent, so I believe that it would be entirely appropriate for this translation to be licensed under the same terms, or a subset of them such as GPL-only; the AGPL is vastly more restrictive than the original license.

I'm also in the boat of "would like to use, but can't" with that license.

**Comment by rsyring** [comment]
Appreciate the effort that went into this library.  No judgement on the license you picked, but just wanted to let you know it is a problem for us: https://github.com/level12/keg-auth/issues/47

**Comment by jaraco** [comment]
I have no objection to releasing this under a more permissive license. I do not know what it would take to change the license. My novice understanding is that the original author or each contribution would need to ascent to the change. I’d be satisfied with an ascent from all 20% contributors. Would someone be willing to shepherd this issue and get the necessary approvals?

**Comment by jaraco** [comment]
@pwdyson , @agronholm : Would you both be willing to allow your contributions to be re-licensed under MIT?

**Comment by agronholm** [comment]
I have no problem with that.

**Comment by pwdyson** [comment]
I have a preference for GPL licences, but as I am not in a position to work on this project nor maintain it, and as Damien used a more permissive licence for the code I originally based this on, I'll agree to re-licencing this under MIT.

**Comment by jaraco** [comment]
Thank you pwdyson. I appreciate the sentiment, and it's with a commensurately heavy heart that I ascent to the re-licensing. The nuance isn't lost on me and I thank you especially for your willingness to allow the more permissive license.

**Comment by amitjindal** [comment]
Thank you very much @jaraco @pwdyson @agronholm
