### ISSUE TITLE
`chocolate chip cookies` become `chocolate chip cooky`

### ISSUE THREAD

**Issue by Abundnce10** [jazzband/inflect#30]
I'm attempting to get the singular form of some food-related words and phrases.  I tried a couple popular phrases and came across this bug:

``` python
import inflect
p = inflect.engine()
p.singular_noun('cookies')
# 'cookie'

p.singular_noun('chocolate chip cookies')
# 'chocolate chip cooky'
```

I believe I'm using the library correctly, so I would expect to see `chocolate chip cookie` instead of `chocolate chip cooky`.

**Comment by thechief389** [comment]
There's a similar problem at #51 where the word `police` gets singularized as `polouse`.

I also had a problem with `species` being singularized as `specy`.
