### ISSUE TITLE
Maintainer?

### ISSUE THREAD

**Issue by AlJohri** [jazzband/inflect#33]
Hi @agronholm, @pwdyson, @benthor, I was wondering if there's a current maintainer for the library.

**Comment by pwdyson** [comment]
I wrote most of this code, but unfortunately I am not in a position to maintain it.

**Comment by agronholm** [comment]
And I took up maintainership only to make it Python 3 compatible. I have no further interest in maintaining it.

**Comment by jaraco** [comment]
I'm interested in seeing this project not languish. If you're willing to grant me ownership to the PyPI project, I'll take on the task of moving inflect into jazzband, automating the acceptance of contributions and releases as much as possible, and lightly guiding contributions.

**Comment by hugovk** [comment]
What's jazzband?

**Comment by jaraco** [comment]
https://jazzband.co/

**Comment by agronholm** [comment]
@jaraco It's been more than a year but I didn't see your message until now. I granted you PyPI maintainership in case you're still interested.

**Comment by agronholm** [comment]
I have no owner level access to this particular repo though so I can't grant you push access, but that's a smaller problem. @pwdyson could help with that.

**Comment by AlJohri** [comment]
I also still use this library and would also be interested in helping out. Transferring ownership to jazzband would be great https://jazzband.co/about/guidelines cc @pwdyson @jaraco

**Comment by hugovk** [comment]
I'll email the owner to see if a transfer is possible, or adding someone else to take care of it.

**Comment by jaraco** [comment]
Great idea. I've already forked the project (/jazzband/inflect), but I'll happily delete that fork if a transfer is approved.

**Comment by hugovk** [comment]
The original author said it sounds good and will take a look on the weekend. Thanks!

**Comment by jaraco** [comment]
I've deleted jazzband/inflect. When you move the repo, please rename it from `inflect.py` to `inflect`. The commits are in the [jaraco fork](/jaraco/inflect.py).

**Comment by pwdyson** [comment]
I've transferred the ownership of this project to jazzband. Thanks @jaraco for taking the initiative on this.

Sorry, I'm not in a position to merge in your commits. I hope by transferring it to Jazzband you can do what needs to be done to satisfy their requirements without too much trouble.

Cheers,
Paul

**Comment by jaraco** [comment]
Thanks @pwdyson for creating this project and for sharing it with jazzband.
