### ISSUE TITLE
Difficulties Installing on Windows + Anaconda

### ISSUE THREAD

**Issue by cogmind** [jazzband/inflect#42]
There appears to be no win32 version available for Anaconda, which makes it difficult to install in individual environments.

**Comment by jaraco** [comment]
This project is pure-Python with no dependencies. It should install under any operating system using Pip. If it's not available for Anaconda, that's probably an issue with the Anaconda ecosystem and not with this project. Please file a ticket with them, and feel free to report back here if there's anything this project needs to do to be supportable in that environment.
