### ISSUE TITLE
case should not effect plurals

### ISSUE THREAD

**Issue by pwdyson** [jazzband/inflect#5]
Entry becomes Entrys but entry becomes entries.

Mentioned in #4.

**Comment by pydsigner** [comment]
I decided to chase down this bug and found the issue: 

```python
# HANDLE ...y

        if lowerword[-1] == 'y':
            if lowerword[-2:-1] in 'aeiou' or len(word) == 1:
                return word + 's'

            if (self.classical_dict['names']):
                if lowerword[-1] == 'y' and word[0] == word[0].upper():
                    return word + 's'

            return word[:-1] + 'ies'
```

Before reaching the default 'y' → 'ies', 'Entry' is seen to be in capitals and is treated as a proper name as long as the classical names option is turned on. 'entries' is lowercase and bypasses that logic.

**Comment by jaraco** [comment]
Looking at the commits, it looks like this was fixed.
