### ISSUE TITLE
Applying plural to an already plural word yields an incorrect result

### ISSUE THREAD

**Issue by SamarthDesai01** [jazzband/inflect#50]
Running p.plural("women") results in "womens"

**Comment by hugovk** [comment]
Junk in, junk out.

> Note that all such methods expect the *singular* form of the word. The results of passing a plural form are undefined (and unlikely to be correct). 

https://github.com/jazzband/inflect/blob/master/README.rst#forming-plurals-and-singulars

**Comment by SamarthDesai01** [comment]
Oh whoops I didn't see that, sorry about that
