### ISSUE TITLE
Singularizing 'police' results in 'polouse'

### ISSUE THREAD

**Issue by catriuspham** [jazzband/inflect#51]
AFIAK, there is no singular form of the word "police", so it should return False in this case.
I guess there is a loop somewhere that replaces "ice" with "ouse". Like in "mice" and "mouse" case.

Source: https://ell.stackexchange.com/questions/4995/when-to-treat-police-as-a-singular-noun-and-a-plural-noun

**Comment by hugovk** [comment]
An explicit example:

```python
Python 3.7.0 (default, Jun 29 2018, 20:13:13)
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import inflect
>>> p = inflect.engine()
>>> print(p.singular_noun("police"))
polouse
```

This comes from here:

https://github.com/jazzband/inflect/blob/10de13826086c16cfbd6156e24caedc9d31b56c5/inflect.py#L2413-L2414

However, I'm not sure if this is a bug. You're asking for the singular noun of "police", which is neither a plural nor singular noun. It's a collective noun.

So I think this is classed under "junk in, junk out":

> Note that all such methods expect the *singular* form of the word. The results of passing a plural form are undefined (and unlikely to be correct). 

https://github.com/jazzband/inflect/blob/master/README.rst#forming-plurals-and-singulars

An exception might be the dialect form known from _The Wire_/Baltimore, "he's a good police", but:

> The module is built around standard British spelling, but is designed to cope with common American variants as well. Slang, jargon, and other English dialects are _not_ explicitly catered for.

**Comment by nielstron** [comment]
If the singular_noun method is intended to return False on definitely singular words, this should be handled though. Especially as there is no other method provided for detecting plurals, this should maybe be considered as a use case.
