### ISSUE TITLE
Releases missing on PyPI?

### ISSUE THREAD

**Issue by rouge8** [jazzband/inflect#66]
The [most recent release on PyPI](https://pypi.org/project/inflect/#history) is 1.0.1, but the repo shows tags for 1.0.2, 2.0.0, 2.0.1, and 2.1.0.

**Comment by jaraco** [comment]
hmm. That shouldn't be the case. I'll investigate.

**Comment by jaraco** [comment]
Oh. I think I was expecting the CI to automatically deploy tagged builds, but I see [it's not](https://travis-ci.org/jazzband/inflect/builds/453142081).

**Comment by jaraco** [comment]
I've cut manual releases of the missing releases and configured the repo to do mechanical releases for the future. Thanks for the report.

**Comment by rouge8** [comment]
Thanks!
