### ISSUE TITLE
Shit program

### ISSUE THREAD

**Issue by kshabahang** [jazzband/inflect#74]
This program is garbage.  It's the dumbest fucking piece of trash code out there.  It thinks words like bus are plural, and turns words like "used" into "useds".  A fucking monkey can come up with better code than this fucking piece of trash.

**Comment by hugovk** [comment]
Garbage in, garbage out.

https://github.com/jazzband/inflect#inflecting-plurals-and-singulars

```python
>>> import inflect
>>> p = inflect.engine()
>>> p.plural("bus")
'buses'
>>>
```

"Used" isn't a noun.

**Comment by kshabahang** [comment]
Hey man,

Sorry I tried deleting the post. Did I not successfully delete it?
Sorry I wrote that in anger, and I shouldn't have.
Appologies...
Let me know if it's still up...

**Comment by kshabahang** [comment]
Let me know if I can somehow make it up to you...

I feel bad about writing a mean comment like that...
