### ISSUE TITLE
plural of Embassy is embassies

### ISSUE THREAD

**Issue by tjoneslo** [jazzband/inflect#78]
plural.inflect("plural_noun('Embassy')")
'Embassys'

**Comment by hugovk** [comment]
It works with lowercase: "embassy" -> "embassies":

```python
Python 3.7.3 (default, Mar 27 2019, 09:23:15)
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import inflect
>>> p = inflect.engine()
>>> p.plural_noun("embassy")
'embassies'
>>> p.plural_noun("Embassy")
'Embassys'
>>>
```

**Comment by eskuat** [comment]
Same issue with "Puppy" word
```
Python 3.6.8 (default, Apr 25 2019, 21:02:35) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
>>> import inflect
>>> p = inflect.engine()
>>> p.plural("Puppy", 2)
'Puppys'
>>> p.plural("puppy", 2)
'puppies'

```

**Comment by jaraco** [comment]
I'm not sure what the right thing to do here. How does inflect handle capitalized words? If it's treating them like proper names, then it would make sense not to pluralize the word.

The docs make some mention of this:

> LEI assumes that a capitalized word is a person's name. So it forms the plural according to the rules for names (which is that you don't inflect, you just add -s or -es). You can choose to turn that behaviour off (it's on by the default, even when the module isn't in classical mode) by calling `` classical(names=0) ``

I'm not sure to what LEI refers, but it seems pertinent.

I'm closing this ticket as invalid, as it's discussing a specific word. If someone wants to file a ticket to describe how the behavior should be different for all capitalized words, that's an option.

**Comment by hugovk** [comment]
LEI must be Lingua/EN/Inflect.pm, the Perl code inflect.py was based in.


* https://github.com/jazzband/inflect/blob/master/README.rst#authors
* https://metacpan.org/pod/Lingua::EN::Inflect
