### ISSUE TITLE
getlist should be wantlist in documentation

### ISSUE THREAD

**Issue by bobbydurrett** [jazzband/inflect#83]
Your documentation has `wantlist` in once place and `getlist` another. `wantlist` works and `getlist` does not.

I think that 

```python
words = p.number_to_words(1234, getlist=True)
```

should be

```python
words = p.number_to_words(1234, wantlist=True)
```

**Comment by hugovk** [comment]
Thanks, please see PR https://github.com/jazzband/inflect/pull/84.
