### ISSUE TITLE
Helper for number & noun together

### ISSUE THREAD

**Issue by kenahoo** [jazzband/inflect#92]
A common use case for this package looks to be something like this:

    # Existing:
    print(f"{n} {p.plural('violation', n)} found")
    -> "0 violations found"
    -> "1 violation found"
    -> "2 violations found"

It would be handy to have a method that outputs the quantified noun for you, to minimize repeating the quantity (e.g. if you're calculating it, you wouldn't have to assign to an intermediate variable):

    # Proposed:
    print(f"p.quantify(n, 'violation')} found")
    -> "0 violations found"
    -> "1 violation found"
    -> "2 violations found"

I'm coming to this package new, apologies if there's already a combined method like this.

**Comment by hugovk** [comment]
`p.no` does almost what you're asking for, except for the zero case it says "no" instead of "0".

https://github.com/jazzband/inflect#numbered-plurals

```python
import inflect

p = inflect.engine()

print("Using p.plural:")
for n in range(0, 3):
    print(f"{n} {p.plural('violation', n)} found")

print()
print("Using p.no:")
for n in range(0, 3):
    print(f"{p.no('violation', n)} found")
```
```
Using p.plural:
0 violations found
1 violation found
2 violations found

Using p.no:
no violations found
1 violation found
2 violations found
```

Is that any use, or do you need to use "0"?

**Comment by kenahoo** [comment]
Thanks, that's perfect - I was deceived by the pun and only thought about the "no" aspect, not the "number" aspect.  =)
